name: On PR For Feature & Bugfix

on:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
      - run: echo "Done!"
#       - name: Checkout
#         uses: actions/checkout@v3
  
#       - name: Set Xcode version
#         run: |
#           ls -l /Applications | grep 'Xcode'
#           sudo xcode-select -s /Applications/Xcode_13.4.app
      
#       - name: Run swift lint
#         run: swiftlint lint
        
#       - name: Run Unit Tests
#         run: |
#           xcodebuild -scheme PackageB test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5'
          
