name: On PR For Feature & Bugfix

on: push

jobs:
  build:
    runs-on: macos-12
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'yml-org/mayo-design-system-ios'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          
      - name: Install Swift Format
        run: brew install swiftformat
        
      - name: Run Swift Format
        run: swiftformat .
  
      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
          echo "there are changes"
          else
          echo "no changes"
          fi
