name: On PR For Feature & Bugfix

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-12
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Swift Format
        run: brew install swiftformat

      - name: Run Swift Format
        run: swiftformat .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Swift format

#       - name: Push changes
#         run: |
#            if [ -n "$(git status --porcelain)" ]; then
#              # There are changes. Stage the file, commit and push
#              git add .
#              git commit -m "Swift Formatted"
#              git push
#            else
#              echo "no changes";
#            fi    
